name: test

on: [push]

permissions: read-all

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: code
        uses: actions/checkout@v4

      - name: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: test
        env:
          GOPRIVATE: github.com/ndx-technologies
        run: go test -cover -coverprofile=coverage.out -covermode=atomic ./...
      
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
